export class UserModel {
    constructor(
        public employeeId: any,
        public firstName: any,
        public middleName: any,
        public lastName: any,
        public dateOfBirth: any,
        public dateOfJoining: any,
        public dateOfLeaving: any,
        public gender : any,
        public profilePic : any,
        public mobilePhone : any,
        public alternatePhone : any,
        public qulaificationDegree : any,
        public degreeOfSpecilization : any,
        public univFrom : any,
        public deg_pass_year : any,	
        public addressLine1: any,
        public addressLine2 : any,
        public addressLine3: any,	
        public perCity: any,
        public perState: any,
        public perZip: any,	
        public crspAdd1: any,
        public crspAdd2: any,	
        public crspAdd3: any,
        public crspCity: any,
        public crspState: any,
        public crspZip: any,
        public country: any,
        public fatherFirstName: any,	
        public fatherMiddleName: any,
        public fatherLastName: any,
        public motheFirstName: any,
        public motherMiddleName: any,
        public motherLastname: any,
        public fatherContact: any,
        public motherContact: any,
        public useField1: any,
        public useField2: any,
        public useField3: any,
        public useField4: any,
        public useField5: any,
        public useField6: any,
        public insertedBy: any,
        public insertedTime: any,
        public updatedBy: any,
        public updatedTime: any,
        public role: any,
        public user: any,
        public userOrganisationId: any,
        public emailId: any,
        public currentPassword: any,
        public passwordLastChangeDate: any,
        public previousChange1: any,
        public previousChange2: any,
        public previousChange3: any,
        public previousChange4: any,
        public previousChange5: any,
        public alterPhone: any,
        public correspondenceAddress1: any,
        public correspondenceAddress2: any,
        public correspondenceAddress3: any,
        public correspondenceCity: any,
        public correspondenceState: any,
        public permanentZip: any,
        public correspondenceZip: any
    ) {  }
  
  }
