export class FormData {
      userId:any= '';
      emailId:any= '';
      firstName:any= '';
      middleName:any= '';
      lastName:any= '';
      dateOfBirth:any= '';
      mobilePhone:any= '';
      alterPhone:any= '';
      correspondenceAddress1:any= '';
      correspondenceAddress2:any= '';
      correspondenceAddress3:any= '';
      correspondenceCity:any= '';
      correspondenceState:any= '';
      permanentZip:any= '';
      correspondenceZip:any= '';
      userOrganisationId:any= '';
      currentPassword:any= '';
      passwordLastChangeDate:any= '';
      previousChange1:any= '';
      previousChange2:any= '';
      previousChange3:any= '';
      previousChange4:any= '';
      previousChange5:any= '';
      studentId:any= '';
      classId:any= '';
      classTeacher:any= '';
      academicYear:any= '';
      gradeObtained:any= '';
      isPromoted:any= '';
      academicReview:any= '';
      gender:any= '';
      permanentAddressLine1:any= '';
      permanentAddressLine2:any= '';
      permanentAddressLine3:any= '';
      permanentCity:any= '';
      permanentState:any= '';
      fatherFirstName:any= '';
      fatherMiddleName:any= '';
      fatherLastName:any= '';
      motherFirstName:any= '';
      motherMiddleName:any= '';
      motherLastName:any= '';
      guardianFirstName:any= '';
      guardianMiddleName:any= '';
      guardianLastName:any= '';
      fatherContact:any= '';
      motherContact:any= '';
      guardianContact:any= '';
      admissionDate:any= '';
      previousSchool:any= '';
clear() {
      this.userId= ''; //user data
      this.emailId= '';
      this.firstName= '';
      this.middleName= '';
      this.lastName= '';
      this.dateOfBirth= '';
      this.mobilePhone= '';
      this.alterPhone= '';
      this.classId= '';
      this.classTeacher= '';
      this.academicYear= '';
      this.gradeObtained= '';
      this.isPromoted= '';
      this.academicReview= '';
      this.gender= '';
      
    this.fatherFirstName= '';//profile data
    this.fatherMiddleName= '';
    this.fatherLastName= '';
    this.motherFirstName= '';
    this.motherMiddleName= '';
    this.motherLastName= '';
    this.guardianFirstName= '';
    this.guardianMiddleName= '';
    this.guardianLastName= '';
    this.fatherContact= '';
    this.motherContact= '';
    this.guardianContact= '';
    this.admissionDate= '';
    this.previousSchool= '';

      this.correspondenceAddress1= ''; //address data
      this.correspondenceAddress2= '';
      this.correspondenceAddress3= '';
      this.correspondenceCity= '';
      this.correspondenceState= '';
      this.permanentZip= '';
      this.correspondenceZip= '';
      this.userOrganisationId= '';
      this.currentPassword= '';
      this.studentId= '';
      this.permanentAddressLine1= '';
      this.permanentAddressLine2= '';
      this.permanentAddressLine3= '';
      this.permanentCity= '';
      this.permanentState= '';
}
}
export class Address {
      correspondenceAddress1: any = ''; //address data
      correspondenceAddress2: any = '';
      correspondenceAddress3: any = '';
      correspondenceCity: any = '';
      correspondenceState: any = '';
      permanentZip: any = '';
      correspondenceZip: any = '';
      userOrganisationId: any = '';
      currentPassword: any = '';
      studentId: any = '';
      permanentAddressLine1: any = '';
      permanentAddressLine2: any = '';
      permanentAddressLine3: any = '';
      permanentCity: any = '';
      permanentState: any = '';
}
export class MyUser{
    userId: any = ''; //user data
    emailId: any = '';
    firstName: any = '';
    middleName: any = '';
    lastName: any = '';
    dateOfBirth: any = '';;
    mobilePhone: any = '';
    alterPhone: any = '';
    classId: any = '';
    classTeacher: any = '';
    academicYear: any = '';
    gradeObtained: any = '';
    isPromoted: any = '';
    academicReview: any = '';
    gender: any = '';
}
export class Profile {
    fatherFirstName: any = '';//profile data
    fatherMiddleName: any = '';
    fatherLastName: any = '';
    motherFirstName: any = '';
    motherMiddleName: any = '';
    motherLastName: any = '';
    guardianFirstName: any = '';
    guardianMiddleName: any = '';
    guardianLastName: any = '';
    fatherContact: any = '';
    motherContact: any = '';
    guardianContact: any = '';
    admissionDate: any = '';
    previousSchool: any = '';
}
